### ISSUE TITLE
Optimize CI Execution Time

### ISSUE THREAD

**Issue by zeppeki** [zeppeki/project-euler-first100#184]
### 現状の問題
現在のCIパイプラインには以下の効率性の問題があります：

1. **実行時間の長さ**
   - 全ジョブが順次実行される
   - 低速テストが全体の実行時間を延ばしている
   - 不要なジョブもPR時に実行される

2. **並列実行の不足**
   - 6つのジョブが独立して実行される
   - 依存関係の重複セットアップ
   - 品質チェックが順次実行される

3. **キャッシュ戦略の非効率性**
   - 各ジョブで独立したキャッシュ
   - 依存関係の重複インストール
   - テスト結果のキャッシュがない

#### Phase 1: 条件付き実行の導入
```yaml
# PR時は軽量チェックのみ
test-fast:
  if: github.event_name == 'pull_request'
  # 高速テストのみ実行

# mainブランチ時は完全チェック
test-full:
  if: github.ref == 'refs/heads/main'
  # 全テスト実行
```

#### Phase 2: 並列実行の最適化
```yaml
# 品質チェックの並列実行
quality:
  steps:
    - name: Run quality checks
      run: |
        uv run ruff check problems/ tests/ &
        uv run mypy problems/ tests/ &
        uv run bandit -r problems/ -f json -o bandit-report.json &
        wait
```

#### Phase 3: テスト分割戦略
```yaml
# 問題別テスト分割
test-problems-1-20:
  run: uv run pytest tests/problems/test_problem_0{01..20}.py -v

test-problems-21-39:
  run: uv run pytest tests/problems/test_problem_0{21..39}.py -v
```

#### Phase 4: キャッシュ戦略の改善
```yaml
- name: Cache Python dependencies
  uses: actions/cache@v4
  with:
    path: |
      ~/.cache/uv
      .venv
    key: ${{ runner.os }}-deps-${{ hashFiles('**/pyproject.toml') }}

- name: Cache test results
  uses: actions/cache@v4
  with:
    path: .pytest_cache
    key: ${{ runner.os }}-pytest-${{ hashFiles('tests/**/*.py') }}
```

#### 実行時間短縮
- **PR時**: 約60%短縮（高速テスト + 品質チェックのみ）
- **mainブランチ**: 約30%短縮（並列実行 + キャッシュ最適化）

#### リソース効率
- 不要なジョブの削除
- 並列実行による効率化
- キャッシュヒット率の向上

#### Phase 1: 条件付き実行
- [ ] PR時とmainブランチ時の実行条件を分離
- [ ] 高速テストのみの軽量CIを実装
- [ ] 不要なジョブの条件付き実行を設定

#### Phase 2: 並列実行最適化
- [ ] 品質チェックの並列実行を実装
- [ ] テストジョブの並列化
- [ ] 依存関係の重複を削減

#### Phase 3: テスト分割
- [ ] 問題別テスト分割の実装
- [ ] 低速テストの分離
- [ ] テスト実行時間の監視

#### Phase 4: キャッシュ最適化
- [ ] 依存関係キャッシュの改善
- [ ] テスト結果キャッシュの導入
- [ ] キャッシュヒット率の監視

### ファイル
- `.github/workflows/ci.yml`

### 検証
- [ ] PR時のCI実行時間が短縮されることを確認
- [ ] mainブランチ時の完全性が保たれることを確認
- [ ] テスト結果が変更されないことを確認
- [ ] キャッシュが正常に動作することを確認

### 参考
- [GitHub Actions Best Practices](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions)
- [Pytest Markers](https://docs.pytest.org/en/stable/how-to/mark.html)
- [GitHub Actions Cache](https://github.com/actions/cache)
