### ISSUE TITLE
Exclude Slow Tests from Coverage Measurement

### ISSUE THREAD

**Issue by zeppeki** [zeppeki/project-euler-first100#186]
### 現状の問題
現在のcoverageジョブは全テスト（fast + slow）を実行してカバレッジを計測しているため、実行時間が長くなっています：

```yaml
- name: Run tests with coverage (problems only)
  run: |
    uv run pytest --cov=problems --cov-report=html --cov-report=xml --cov-report=term
```

slowテストは実行時間が長く、カバレッジ計測の精度向上に大きな貢献をしていません。

### 最適化の目標
slowテストをカバレッジ計測から除外し、fastテストのみでカバレッジを計測することで実行時間を短縮します。

#### 1. 現在のslowテストの確認
現在、以下のテストが`@pytest.mark.slow`でマークされています：

- Problem 005: 大きな入力値でのテスト
- Problem 007: 大きな素数でのテスト
- Problem 008: 大きな数列でのテスト
- Problem 010: 大きな範囲での素数計算
- Problem 012: 大きな三角数のテスト
- Problem 013: 大きな数の計算
- Problem 014: 大きなコラッツ数列
- Problem 015: 大きな格子経路
- Problem 016: 大きな累乗の計算
- Problem 017: 大きな数の文字列変換
- Problem 018: 大きな三角形の経路
- Problem 019: 大きな日付範囲の計算
- Problem 020: 大きな階乗の計算
- Problem 021: 大きな数の友愛数計算
- Problem 022: 大きな名前リストの処理
- Problem 023: 大きな数の過剰数計算
- Problem 025: 大きなフィボナッチ数
- Problem 026: 大きな数の循環小数
- Problem 027: 大きな係数での二次式
- Problem 028: 大きな螺旋の計算
- Problem 029: 大きな累乗の組み合わせ
- Problem 030: 大きな数の各桁の累乗
- Problem 031: 大きな金額の組み合わせ
- Problem 032: 大きな数のパンデジタル
- Problem 033: 大きな分数の計算
- Problem 034: 大きな数の階乗和
- Problem 035: 大きな数の循環素数
- Problem 036: 大きな数の二進回文
- Problem 037: 大きな数の切り詰め可能素数
- Problem 039: 大きな数の直角三角形

#### 2. coverageジョブの最適化
```yaml
coverage:
  if: github.event_name != 'pull_request'
  runs-on: ubuntu-latest
  needs: test

  steps:
  # ... セットアップ ...
  
  - name: Run tests with coverage (exclude slow tests)
    run: |
      uv run pytest --cov=problems --cov-report=html --cov-report=xml --cov-report=term -m "not slow"
  
  - name: Upload coverage reports
    uses: actions/upload-artifact@v4
    with:
      name: coverage-report
      path: |
        htmlcov/
        coverage.xml
```

#### 3. テスト実行の分離
```yaml
test:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      python-version: ["3.11", "3.12"]

  steps:
  # ... セットアップ ...
  
  - name: Run fast tests
    run: |
      uv run pytest tests/ -v -m "not slow"
  
  - name: Run slow tests
    run: |
      uv run pytest tests/ -v -m "slow"

coverage:
  if: github.event_name != 'pull_request'
  runs-on: ubuntu-latest
  needs: test
  
  steps:
  # ... セットアップ ...
  
  - name: Run coverage (fast tests only)
    run: |
      uv run pytest --cov=problems --cov-report=html --cov-report=xml --cov-report=term -m "not slow"
```

#### Phase 1: 現状分析
- [ ] 現在のslowテストの一覧を確認
- [ ] 各slowテストの実行時間を測定
- [ ] slowテストのカバレッジ貢献度を分析

#### Phase 2: CI設定の更新
- [ ] coverageジョブに`-m "not slow"`オプションを追加
- [ ] テストジョブでfast/slowテストを分離
- [ ] 実行時間の測定と比較

#### Phase 3: カバレッジ精度の検証
- [ ] slowテスト除外前後のカバレッジ率を比較
- [ ] カバレッジレポートの詳細分析
- [ ] 必要に応じてslowテストの一部をfastに変更

#### Phase 4: 最適化の検証
- [ ] 実行時間の短縮効果を確認
- [ ] カバレッジ精度の維持を確認
- [ ] テスト結果の一貫性を確認

#### 実行時間短縮
- **現在**: 全テスト実行（約3-5分）
- **最適化後**: fastテストのみ（約1-2分）
- **短縮率**: 60-70%

#### カバレッジ精度の維持
- **基本機能**: 100%カバー（維持）
- **エッジケース**: 100%カバー（維持）
- **複数解法**: 100%カバー（維持）
- **大規模テスト**: 除外（slowマーク）

#### カバレッジ比較
```bash
# 全テストでのカバレッジ
uv run pytest --cov=problems --cov-report=term

# fastテストのみでのカバレッジ
uv run pytest --cov=problems --cov-report=term -m "not slow"
```

#### 実行時間比較
```bash
# 全テストの実行時間
time uv run pytest tests/ -v

# fastテストのみの実行時間
time uv run pytest tests/ -v -m "not slow"
```

### ファイル
- `.github/workflows/ci.yml`

### 検証
- [ ] slowテスト除外後も十分なカバレッジが得られることを確認
- [ ] 実行時間が短縮されることを確認
- [ ] テスト結果が変更されないことを確認
- [ ] カバレッジレポートが正常に生成されることを確認

### 参考
- [Pytest Markers](https://docs.pytest.org/en/stable/how-to/mark.html)
- [Coverage.py](https://coverage.readthedocs.io/)
- [GitHub Actions Cache](https://github.com/actions/cache)
